name: Build ZMK firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-setuptools python3-wheel xz-utils file \
            make gcc gcc-multilib libncurses-dev libusb-1.0-0-dev

      - name: Setup west and Zephyr SDK
        run: |
          pip3 install --user west
          west init -l config
          west update
          west zephyr-export
          pip3 install --user -r zephyr/scripts/requirements.txt

      - name: Build firmware
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=my_6x12_ioe
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/zephyr/zephyr.hex
